title: Google Photos
description: Portfolio where the insiders of Google Photos can be known.
show_downloads: false
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
